#CC=clang
#SAN_FLAGS=-fsanitize=address -O1 -fno-omit-frame-pointer

WARN_FLAGS=
#WARN_FLAGS= -Wno-nullability-completeness   -std=c11 -Wall -Wc++-compat -Wextra -Wunused -Waggregate-return -Wbad-function-cast -Wcast-align -Wdeclaration-after-statement -Wdisabled-optimization -Wdiv-by-zero -Wendif-labels -Werror-implicit-function-declaration -Wfloat-equal -Wformat=2 -Wframe-larger-than=4096 -Winit-self -Winline -Wmissing-declarations -Wmissing-format-attribute -Wmissing-noreturn -Wmissing-prototypes -Wnested-externs -Wold-style-definition -Wpacked -Wpointer-arith -Wredundant-decls -Wshadow -Wsign-compare -Wstrict-overflow -Wstrict-prototypes -Wswitch-enum -Wunreachable-code -Wwrite-strings -Wno-missing-field-initializers -Wno-system-headers -Wno-unused-parameter -Wswitch-bool -Wlogical-not-parentheses -Wsizeof-array-argument -Wshorten-64-to-32

DEBUG_FLAGS=-g3 $(WARN_FLAGS)
#DEBUG_FLAGS=-g3 -DSV_DEBUG=3

SVLIB=libsv.a
SVLIBSRCS=sv.c option.c write.c read.c
SVLIBHDRS=sv.h sv_internal.h

LIBS=$(SVLIB)

EXSRCS=example.c sv2c.c gen.c
EXAMPLES=example sv2c gen
TESTSRCS=svtest.c

SRCS=$(EXSRCS) $(SVLIBSRCS) $(TESTSRCS) $(SVLIBHDRS)
EXES=$(EXAMPLES)
TESTS=svtest

CLEANFILES=$(EXES) $(LIBS) $(TESTS) \
stamp-h1

TEST_FILES=test1.csv \
zero.tsv \
one.tsv \
test1.tsv

FILES=README.md \
GNUMakefile \
AUTHORS ChangeLog COPYING COPYING.LIB INSTALL LICENSE.txt LICENSE-2.0.txt \
NOTICE NEWS README configure.ac Makefile.am \
$(TEST_FILES) \
$(SRCS)

PACKAGE=libsv
VERSION=1.0.0

PV=$(PACKAGE)-$(VERSION)
TARBALL=$(PV).tar.gz

LDFLAGS=$(DEBUG_FLAGS) $(SAN_FLAGS)
CPPFLAGS=$(DEBUG_FLAGS) -I. -DHAVE_UNISTD_H -DHAVE_ERRNO_H
CFLAGS=$(SAN_FLAGS)

SVLIBOBJS=$(SVLIBSRCS:.c=.o)

all: $(LIBS) $(EXES)

# Library deps
sv.c: sv.h
$(SVLIBSRCS): sv_internal.h

$(SVLIB): $(SVLIBOBJS)
	$(AR) rv $@ $?

# Object deps
example: example.o $(SVLIB)
svtest: svtest.o $(SVLIB)
sv2c: sv2c.o $(SVLIB)
gen: gen.o $(SVLIB)

# Source Deps
sv2c.c: sv.h
svtest.c: sv.h
example.c: sv.h
gen.c: sv.h

dist: $(FILES)
	rm -rf $(PV) && \
	mkdir $(PV) && \
	cp $(FILES) $(PV) && \
	tar cfz $(TARBALL) $(PV) && \
	rm -rf $(PV)

clean:
	rm -f *.o *~ *.tar.gz $(CLEANFILES)

check: $(TESTS)
	@rc=0; \
	for t in $(TESTS); do \
	  echo "Running test $$t"; \
	  ./$$t; \
	  status=$$?; \
	  if test $$status != 0; then \
	    rc=1; \
	  fi; \
	done; \
	exit $$rc
